name: Provision Droplets

on:
  workflow_dispatch:
    inputs:
      ec2-name:
        description: Droplets name
        required: true
        default: 'App Server'
        type: string
jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DROPLET_TOKEN }}
      - name: Additional images
        run: doctl compute image list-user
      - name: Provision Droplets
        run: doctl compute droplet create ysg-test --image 145306799 --size s-8vcpu-16gb-amd --region sfo3 --wait
