name: Provision Droplets

on:
  workflow_dispatch:
    inputs:
      ec2-name:
        description: Droplets name
        required: true
        default: 'App Server'
        type: string
jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
     
